name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Verify formatting
        run: gofmt -l . | tee /tmp/gofmt.txt && test ! -s /tmp/gofmt.txt
      - name: Run unit tests with coverage
        run: go test ./... -coverprofile=coverage.out
      - name: Enforce coverage threshold
        run: |
          go tool cover -func=coverage.out | awk 'END {print $3}' | sed 's/%//' | awk '{if ($1+0 < 80) {exit 1}}'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - uses: golangci/golangci-lint-action@v4
        with:
          install-mode: goinstall
          version: latest
          args: --timeout=5m

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Build binaries
        run: ./scripts/build.sh
